export const DUMMY_SERVICE = {
  sections: [
    {
      name: "name 1",
      services: [
        {
          name: "name",
          desc: "desc",
          serviceType: "serviceType",
          billType: "billType",
          unit: "unit",
          estimate: "estimate",
          qty: 0,
          price: 1,
          discount: 1,
          markUp: 1,
          tolBudget: 0,
        },
        {
          name: "name",
          desc: "desc",
          serviceType: "serviceType",
          billType: "billType",
          unit: "unit",
          estimate: "estimate",
          qty: 0,
          price: 1,
          discount: 1,
          markUp: 1,
          tolBudget: 0,
        },
      ],
    },
    {
      name: "name 2",
      services: [
        {
          name: "name",
          desc: "desc",
          serviceType: "serviceType",
          billType: "billType",
          unit: "unit",
          estimate: "estimate",
          qty: 0,
          price: 1,
          discount: 1,
          markUp: 1,
          tolBudget: 0,
        },
        {
          name: "name",
          desc: "desc",
          serviceType: "serviceType",
          billType: "billType",
          unit: "unit",
          estimate: "estimate",
          qty: 0,
          price: 1,
          discount: 1,
          markUp: 1,
          tolBudget: 0,
        },
      ],
    },
  ],
};
