export const formErrorCode = {
  REGISTERED_EMAIL: "REGISTERED_EMAIL",
  WRONG_EMAIL_OR_PASSWORD: "WRONG_EMAIL_OR_PASSWORD",
  INVALID_CODE: "INVALID_CODE",
  INVALID_DATA: "INVALID_DATA",
};

export const LIST_FORM_ERROR_CODE = Object.values(formErrorCode);
