name: deploy staging webapp

on:
  push:
    branches:
      - dev

jobs:
    lintTest:
        name: Lint
        runs-on: ubuntu-latest
        steps:
        - name: Clone Repository
          uses: actions/checkout@v2
        - name: Install Dependencies
          run: |
            echo "Running Install Dependencies ... "
            yarn
        - name: Run Linting
          run: |
            echo "Running lint testing ... "
            yarn lint 
          env: 
            CI: true
    securityCheck:
        name: Security Check
        runs-on: ubuntu-latest
        steps:
            - name: Check for security
              run: |
                echo "Running Security Check"
                sleep 5s;
                echo "Running Security Check 1"
                sleep 5s;
                echo "Running Security Check 2"
                sleep 5s;
                echo "Running Security Check 3"
                sleep 5s;
    deploy:
        name: Development
        runs-on: ubuntu-latest
        needs:  [lintTest, securityCheck]
        steps:
            - name: Install Dependencies
              run: |
                echo "Deployment in Progress .. "
